services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    #myapp:
    # build:
    #  context: .
    # dockerfile: Dockerfile
    #environment:
    # - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mydatabase'
    #- 'SPRING_DATASOURCE_USERNAME=myuser'
    #- 'SPRING_DATASOURCE_PASSWORD=secret'
    #depends_on:
    # - postgres
    #ports:
    # - '8080:8080'